# Generated by Django 3.2.13 on 2022-06-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20220607_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='sas_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
