# Generated by Django 3.2.13 on 2022-06-10 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_sas_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='veriried_at',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
