# Generated by Django 3.2.13 on 2022-06-10 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_file_veriried_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='veriried_at',
            new_name='verified_at',
        ),
    ]
